# Generated by Django 5.1.7 on 2025-03-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_adi', models.CharField(max_length=255)),
                ('makale_orjinal_path', models.FileField(upload_to='makaleler/orjinal/')),
                ('makale_anonim_path', models.FileField(blank=True, null=True, upload_to='makaleler/anonim/')),
                ('makale_yanitli_path', models.FileField(blank=True, null=True, upload_to='makaleler/yanitli/')),
                ('makale_tarih', models.DateTimeField(auto_now_add=True)),
                ('hakem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to='user.customuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_articles', to='user.customuser')),
            ],
        ),
    ]
