# Generated by Django 5.1.7 on 2025-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='aes_key_enc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
