# Generated by Django 5.1.7 on 2025-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_aes_key_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='iv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='aes_key_enc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
