# Generated by Django 5.1.7 on 2025-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_iv_alter_article_aes_key_enc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='iv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
