# Generated by Django 5.1.7 on 2025-03-16 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0003_article_iv_alter_article_aes_key_enc'),
        ('user', '0003_user_rsa_private_key_user_rsa_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aes_key_enc', models.CharField(blank=True, max_length=500, null=True)),
                ('iv', models.CharField(blank=True, max_length=500, null=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
