# Generated by Django 5.1.7 on 2025-03-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifreleme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_access',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file_access',
            old_name='user_id',
            new_name='user',
        ),
    ]
