# Generated by Django 5.1.7 on 2025-03-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_iv_alter_article_aes_key_enc'),
        ('sifreleme', '0002_rename_file_id_file_access_file_and_more'),
        ('user', '0003_user_rsa_private_key_user_rsa_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aes_key_enc', models.CharField(max_length=500)),
                ('iv', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='File_access',
        ),
    ]
