# Generated by Django 5.1.7 on 2025-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifreleme', '0003_fileaccess_delete_file_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='aes_key_enc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='iv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
