# Generated by Django 5.1.7 on 2025-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('yazar', 'Yazar'), ('editor', 'Editör'), ('hakem', 'Hakem')], default='yazar', max_length=10)),
            ],
        ),
    ]
