# Generated by Django 5.1.7 on 2025-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rsa_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
